---
- name: configure NetworkManager
  lineinfile:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4['interface'] }}"
    regexp: '^{{ item }}='
    line: '{{ item }}=yes'
    state: present
    create: yes
  with_items:
  - 'USE_PEERDNS'
  - 'NM_CONTROLLED'

- name: enable and start NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: yes

# TODO(shadower): add the flannel interface tasks from post-provision-openstack.yml

- name: Ensure hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ hostvars[item]['private_v4'] }} {{ hostvars[item]['ansible_hostname'] + '.' + openshift_openstack_full_dns_domain }}"
  with_items: "{{ groups['cluster_hosts'] }}"
  when: hostvars[item]['private_v4'] is defined
